# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    attributes: {}
    worker-type: linux
    worker:
        docker-image: {in-tree: mdbook}
        max-run-time: 3600
    # treeherder:
    #     kind: test
    #     platform: tests/opt
    #     tier: 1
    run:
        using: run-task
        cwd: '{checkout}'

jobs:
    build:
        description: "Build documentation with the latest changes"
        # treeherder:
        #     symbol: mdbook
        run:
            command: >-
                mdbook build doc &&
                tar -zcv -C doc/book -f /builds/worker/artifacts/book.tar.gz .
